language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_install:
  - phpenv rehash
  - sudo apt-get update -qq
  - sudo apt-get install -qq re2c valgrind

install:
  - ./generate
  - cd ext
  - export CFLAGS="-g3 -O1 -fno-delete-null-pointer-checks -Wall -fvisibility=hidden"
  - phpize
  - ./configure --silent --enable-zephir-parser
  - make -j2
  - sudo make install
  - cd ..
  - echo 'extension="zephir_parser.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - ulimit -c unlimited || true

script:
  - valgrind --read-var-info=yes --error-exitcode=1 --fullpath-after= --track-origins=yes --leak-check=full phpunit --debug
